spring.application.name=TaskController
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view is Default true but now Explicit false for better performance
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect__-Cause WARNING
# Swagger UI Path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
# Show enum as string instead of index
springdoc.default-produces-media-type=application/json